### ISSUE TITLE
Real issue

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [Lexium-Tech/GIAPB-test#2]
I have an issue

**Comment by GIAPB** [comment]
Hello!    

It seems that your current issue has been marked for closing by me or a human.    
 As a robot I have commands and right now it is to close this issue.    
  Thank you for reporting this issue and if this issue continues to persist or you happen to have another, feel free to open another issue.    

If you feel this was done in error. Contact the humans.    

Best of luck going forward,    
GIAPB, your friendly GitHub bot
